sudo: false

matrix:
  include:
    - rvm: 2.3.1
      env:
        - MONGOID_VERSION=6
    - rvm: 2.3.1
      env:
        - MONGOID_VERSION=5
    - rvm: 2.2
      env:
        - MONGOID_VERSION=4
    - rvm: 2.1
      env:
        - MONGOID_VERSION=3

services: mongodb

addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
